INSERT INTO editoriales (nombre,ciudad) VALUES ('ALBA','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('ANAYA','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('AFHA','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('LUMEN','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('PLAZA Y JANES','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('RAMON SOPENA','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('EDICIONES B','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('CEGAL','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('EL PAIS','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('CATEDRA','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('SUMA DE LETRAS','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('SM','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('ALIANZA','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('SOL 90','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('TUSQUETS','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('EVEREST','LEON');
INSERT INTO editoriales (nombre,ciudad) VALUES ('JUVENTUD','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('TABLE RONDE','PARIS');
INSERT INTO editoriales (nombre,ciudad) VALUES ('ESPASA CALPE','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('ORBIS','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('EDICOLA','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('ANAGRAMA','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('POMAIRE','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('OLYMPIA',null);
INSERT INTO editoriales (nombre,ciudad) VALUES ('SOPENA','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('PLANETA','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('CRITICA','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('MOLINO','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('COMPAÑÍA EUROPEA DE COMUNICACIÓN','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('MINOTAURO','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('ISCUSSTVO','MOSCU');
INSERT INTO editoriales (nombre,ciudad) VALUES ('DESTINO','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('G P','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('RBA','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('BRUGUERA','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('GREDOS','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('MONDADORI','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('KALANDRAKA','SEVILLA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('SALVAT','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('CELESTE','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('EDICOMUNICACION','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('S A DE PROMOCIONES Y EDICIONES','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('MAGISTERIO ESPAÑOL','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('ALFAGUARA','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('ENCUENTRO','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('PANAMERICA','COLOMBIA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('EDIMAT','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('PENINSULA','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('EDHASA','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('EL MUNDO','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('SIRUELA','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('CUADERNOS PARA EL DIALOGO','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('EL ALEPH','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('ELFOS','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('EDISERVICIOS','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('TURPIAL','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('SEIX BARRAL','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('ZERO','BILBAO');
INSERT INTO editoriales (nombre,ciudad) VALUES ('LE LIVRE DE POCHE','PARIS');
INSERT INTO editoriales (nombre,ciudad) VALUES ('ABC','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('BOSCH','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('CLUB INTERNACIONAL DEL LIBRO','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('JOSE J OLAÑETA','PALMA DE MALLORCA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('NOGUER','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('SALAMANDRA','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('COMUNICACIÓN Y PUBLICACIONES','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('GRUPO 62','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('ULTRAMAR','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('EDICIONES DE BRONCE','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('GRIJALBO','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('CARALT','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('AGUILAR','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('MENSAJERO','BILBAO');
INSERT INTO editoriales (nombre,ciudad) VALUES ('EDITORES MEJICANOS UNIDOS','MEJICO');
INSERT INTO editoriales (nombre,ciudad) VALUES ('EDAF','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('GUADARRAMA','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('FOLIO','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('GAVIOTA','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('VALDEMAR','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('MAEVA','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('LIBROS DEL ASTEROIDE','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('CEAC','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('HISPAMERICA','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('DEBATE','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('EMECE','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('DEBOLSILLO','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('SANTILLANA','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('DE LA TORRE','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('ANETO','ZARAGOZA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('HARLEGUIN IBERICA','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('ACANTILADO','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('EDITORIAL MINUSCULA','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('EASY READERS','COPENHAGUE');
INSERT INTO editoriales (nombre,ciudad) VALUES ('M E EDITORES','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('BABILONIA','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('ALPHA DECAY','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('LOSADA','BUENOS AIRES');
INSERT INTO editoriales (nombre,ciudad) VALUES ('SIETE LEGUAS','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('EDICIONES IBERICAS','AVILA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('RUBIÑOS','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('EASSY READERS','COPENHAGUE');
INSERT INTO editoriales (nombre,ciudad) VALUES ('SERVILIBRO','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('LA GAYA CIENCIA','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('SARPE','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('ESTUDIO DIDACTICO','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('HERDER','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('LIBRA','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('INSTITUTO HISPANOARABE DE CULTURA','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('DIPUTACION DE SALAMANCA','SALAMANCA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('LABOR','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('GRUPO TORMES','SALAMANCA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('AGRUPACION NACIONAL DEL COMERCIO DEL LIBRO','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('AMARU','SALAMANCA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('ALTAYA','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('GIRTESS','SALAMANCA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('CAJA DUERO','SALAMANCA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('FUNDACION GERMAN SANCHEZ RUIPEREZ','SALAMANCA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('OCEANO','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('MIÑON','VALLADOLID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('TEMAS DE HOY','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('CAJA SALLAMANCA Y SORIA','SALAMANCA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('JUNTA DE CASTILLA Y LEON','VALLADOLID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('BIBLIOTEX','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('ARNAO','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('TURNER','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('EDILESA','LEON');
INSERT INTO editoriales (nombre,ciudad) VALUES ('GABRIEL RIVAS','BEJAR');
INSERT INTO editoriales (nombre,ciudad) VALUES ('PILAR BLANCO OVIEDO','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('THULE','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('ICARIA','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('AMBITO','VALLADOLID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('CARO RAGGIO','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('EMPRESA PUBLICA DON QUIJOTE 2005',null);
INSERT INTO editoriales (nombre,ciudad) VALUES ('IBERICAS','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('EL SOL','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('OLLERO Y RAMOS','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('CASTALIA','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('ARGOS VERGARA','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('FORUM','BEJAR');
INSERT INTO editoriales (nombre,ciudad) VALUES ('CONSORCIO SALAMANCA 2002','SALAMANCA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('JULIO LAGO ALONSO','BURGOS');
INSERT INTO editoriales (nombre,ciudad) VALUES ('SOCIEDAD DE EDUCACION ATENAS','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('MARTIN VAQUERO','BEJAR');
INSERT INTO editoriales (nombre,ciudad) VALUES ('ROCAEDITORIAL','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('PRENSA ESPAÑOLA','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('ESTELA','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('L F','SALAMANCA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('CIRCULO DE LECTORES','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('MENDEZ Y MOLINA','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('LENGUA DE TRAPO','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('ARES Y MARES','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('EDITORA NACIONAL','MEJICO');
INSERT INTO editoriales (nombre,ciudad) VALUES ('SOL','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('R Y JJ OLAÑETA','PALMA DE MALLORCA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('ARIEL','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('NUEVAS EDICIONES DE BOLSILLO','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('ZETA','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('SECRETARIADO NACIONAL DE CATEQUESIS','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('ESCUELA ESPAÑOLA','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('PIRAMIDE','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('ASETES','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('UNIVERSIDAD DE GRANADA','GRANADA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('BIBLIOTECA DE AUTORES CRISTIANOS','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('NARCEA','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('ANABAD','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('URANO','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('PRADO','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('MARCOS MARTIN','SALAMANCA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('ASOCIACION CELCE','VALENCIA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('DEDALO','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('SAL TERRAE','SANTANDER');
INSERT INTO editoriales (nombre,ciudad) VALUES ('CCS','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('MINISTERIO DE EDUCACION NACIONAL','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('PEREA','CIUDAD REAL');
INSERT INTO editoriales (nombre,ciudad) VALUES ('FUNDACION ARTE Y TECNOLOGIA. TELEFONICA',null);
INSERT INTO editoriales (nombre,ciudad) VALUES ('MARTINEZ ROCA','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('H BLUME','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('NESTLE AEPA','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('ARTSANA','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('MEDICI','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('PALABRA','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('API','SALAMANCA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('LA GACETA','SALAMANCA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('TRIBUNA','SALAMANCA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('EL ADELANTO','SALAMANCA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('CENTRO DE ESTUDIOS SALMANTINOS','SALAMANCA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('DISTRIMAPAS','SALAMANCA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('UNIVERSIDAD DE SALAMANCA','SALAMANCA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('IES GARCIA BERNALT','SALAMANCA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('AYUNTAMIENTO DE SALAMANCA','SALAMANCA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('COLEGIO OFICIAL DE ARQUITECTOS','SALAMANCA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('CERVANTES','SALAMANCA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('PASAJE DE LAS LETRAS','VALLADOLID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('EDICIONES IRREVERENTES','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('IOATO','SALAMANCA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('CIT','SALAMANCA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('TURISMO DE SALAMANCA','SALAMANCA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('MANCOMUNIDAD DE ENTRESIERRAS','SALAMANCA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('FUNDACION SALAMANCA CIUDAD DE CULTURA','SALAMANCA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('PUBLICACIONES REGIONALES','SALAMANCA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('EDILUX','SALAMANCA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('MARTESA','GIJON');
INSERT INTO editoriales (nombre,ciudad) VALUES ('LANCIA','LEON');
INSERT INTO editoriales (nombre,ciudad) VALUES ('AL PLATA','SALAMANCA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('FUNDACION RAMOS DE CASTRO','SALAMANCA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('AVELINA SERRANO MUÑOZ','SALAMANCA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('MEDITERRANEO','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('EDICAL','VALLADOLID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('LIMITE','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('MICHELIN','FRANCIA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('SCHMID VERLAG','VIENA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('ACENTO','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('DEVIAJES','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('GRANICA','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('DESNIVEL','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('LAROUSSE','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('MINISTERIO DE FOMENTO','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('STVDIO','SANTANDER');
INSERT INTO editoriales (nombre,ciudad) VALUES ('TEMPORA','SALAMANCA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('SELECCIONES DEL READER´S DIGEST','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('SUSAETA','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('DIPUTACION DE GUIPOZCOA','SAN SEBASTIAN');
INSERT INTO editoriales (nombre,ciudad) VALUES ('GAMMA','TOURNAI');
INSERT INTO editoriales (nombre,ciudad) VALUES ('LA VANGUARDIA','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('PATRONATO MUNICIPAL DE TURISMO','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('CONTRAFORMA','ZAMORA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('MONTERREY','LA CORUÑA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('CONSEJO GENERAL DE CASTILLA Y LEON','VALLADOLID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('GAESA','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('LONELY PLANET','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('GREFOL','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('LIBSA','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('CASTELL','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('DIPUTACION DE VALLADOLID','VALLADOLID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('L B PRINCE','VIRGINIA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('DIPUTACION DE ZAMORA','ZAMORA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('ESCUDO DE ORO','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('DIRECCION GENERAL DE POLITICA TURISTICA','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('HERNAN ALONSO','PONFERRADA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('SOTABUR','SORIA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('CAJAMADRID','VALLADOLID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('TREA','OVIEDO');
INSERT INTO editoriales (nombre,ciudad) VALUES ('LA LIBRERÍA','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('TRIANGLE POSTALS','MENORCA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('CONCELLO DE CELANOVA','CELANOVA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('NATIONAL GEOGRAPHIC','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('FRANCISCO CORTES','SALAMANCA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('JUCAR','GIJON');
INSERT INTO editoriales (nombre,ciudad) VALUES ('CAYETANO ENRIQUEZ DE SALAMANCA','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('CORTES DE ARAGON','ZARAGOZA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('SALIMOS','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('COMARES','GRANADA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('AYUNTAMIENTO DE BILBAO','BILBAO');
INSERT INTO editoriales (nombre,ciudad) VALUES ('ARS MAGNA','PALENCIA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('CALAMO','PALENCIA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('EDICIONS XERAIS DE GALICIA','VIGO');
INSERT INTO editoriales (nombre,ciudad) VALUES ('EDICIONS DO CUMIO','VIGO');
INSERT INTO editoriales (nombre,ciudad) VALUES ('LES EDITIONS DU LOMBARD','BRUSELAS');
INSERT INTO editoriales (nombre,ciudad) VALUES ('LA GOLETTE','PARIS');
INSERT INTO editoriales (nombre,ciudad) VALUES ('ANTONIO MACHADO LIBROS','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('EL TRANSBORDADOR DE VIZCAYA','BILBAO');
INSERT INTO editoriales (nombre,ciudad) VALUES ('PICU URRIELLU','GIJON');
INSERT INTO editoriales (nombre,ciudad) VALUES ('COMPAÑÍA LIMICLE DE COMUNICACIÓN','MERIDA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('DIPUTACION DE SORIA','SORIA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('TIERRA DE FUEGO','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('WILIBALDO FERNANDEZ','SAHAGUN');
INSERT INTO editoriales (nombre,ciudad) VALUES ('FAMP','OÑA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('PP CARMELITAS DESCALZOS','SALAMANCA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('ELANIO AZUL','SALAMANCA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('MUSEO NACIONAL DEL PRADO','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('PAIDOS','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('PRESA','SALAMANCA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('TEIDE','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('AGATA','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('REAL ACADEMIA ESPAÑOLA','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('ACV','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('MINISTERIO DE OBRAS PUBLICAS','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('TURESPAÑA','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('COLEGIO OFICIAL DE ARQUITECTOS DE LEON','LEON');
INSERT INTO editoriales (nombre,ciudad) VALUES ('VOX','INGLATERRA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('IDIOMA RUSO','MOSCU');
INSERT INTO editoriales (nombre,ciudad) VALUES ('BIBLIOGRAF','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('TASCHEN','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('LOFT','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('FUNDACION JUAN MARCH','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('LUNWERG','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('PALACE EDITIONS','ITALIA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('TETRO REAL','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('GLOBUS','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('CARROGIO','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('RICORDI AMERICANA','BUENOS AIRES');
INSERT INTO editoriales (nombre,ciudad) VALUES ('ANTARTIDA','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('ANDANTINO','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('GIGILI','MEJICO');
INSERT INTO editoriales (nombre,ciudad) VALUES ('ELECTA','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('TEATRO REAL','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('GUGGENHEIM','BILABAO');
INSERT INTO editoriales (nombre,ciudad) VALUES ('FUNDACION LA CAIXA','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('RAYUELA','VALENCIA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('HISTORIA 16','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('ANGEL VAZQUEZ',null);
INSERT INTO editoriales (nombre,ciudad) VALUES ('LUIS CORTES VAZQUEZ','SALAMANCA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('SANTOS SAN CRISTOBAL','MONDOÑEDO');
INSERT INTO editoriales (nombre,ciudad) VALUES ('NGV','COLONIA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('TULIPAN','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('CLAVE','BILBAO');
INSERT INTO editoriales (nombre,ciudad) VALUES ('INDUSTRIAL QUESERA MENORQUINA','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('PRIMERA PLANA','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('TIEMPO LIBRE','BILBAO');
INSERT INTO editoriales (nombre,ciudad) VALUES ('TASADA Y BELTRAN','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('DANONE','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('KETRES','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('PESCANOVA','PONTEVEDRA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('IRU','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('CONICA','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('MIDESA','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('CEDAG','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('MINISTERIO DE SANIDAD','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('KOIPE','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('MANUEL RIVAS','SALAMANCA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('CRYSESA','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('WOODWARD','SOTAH');
INSERT INTO editoriales (nombre,ciudad) VALUES ('ZARZALEJOS','MARIA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('CAMIÑO DO FARO','LA CORUÑA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('LOS QUESOS DE FRANCIA',null);
INSERT INTO editoriales (nombre,ciudad) VALUES ('MINISTERIO DE EDUCACION','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('BRUÑO','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('ICE','SALAMANCA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('DOSSAT','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('MARIN','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('PARANINFO','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('EDUNSA','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('UTEHA','MEJICO');
INSERT INTO editoriales (nombre,ciudad) VALUES ('MCBRAW HILL LATINO AMERICANA','COLOMBIA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('NELSON','GRAN BRETAÑA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('VIDAL LLENAS','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('INSTITUTO BELGA DE INFORMACION','BRUSELAS');
INSERT INTO editoriales (nombre,ciudad) VALUES ('RIALP','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('FOLLAS NOVAS','SANTIAGO DE COMPOSTELA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('COMUNIDAD DE MADRID','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('INSTITUTO NACIONAL DE METEOROLOGIA','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('INSTITUTO GEOGRAFICO NACIONAL','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('VICENS VIVES','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('MUNDO ACTUAL DE EDICIONES','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('OMEGA','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('JOSE BATLLO','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('ALTEA','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('DE VECHI','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('IMPEDIMENTA','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('AYUNTAMIENTO DE MADRID','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('JOVER','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('RIODUERO','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('OIKOS TAU','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('MUNDO NATURA','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('SIGLO XXI','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('REVISTA DE OCCIDENTE','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('MARCIAL PONS','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('TRIGO','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('ISTMO','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('EL ALBIR','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('FONDO DE CULTURA ECONOMICA','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('UNIVERSIDAD DE NAVARRA','PAMPLONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('ANUBAR','ZARAGOZA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('FISA','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('REPSOL',null);
INSERT INTO editoriales (nombre,ciudad) VALUES ('ANIBAL NUÑEZ','SALAMANCA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('DAIMON','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('COMPO','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('XUNTA DE GALICIA','SANTIAGO DE COMPOSTELA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('TOMO','MEXICO D F');
INSERT INTO editoriales (nombre,ciudad) VALUES ('ALMENA','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('ANFIL','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('EL JUEVES','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('BURLINGTON BOOKS','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('EDELVIVES','ZARAGOZA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('HEMMA','SAN SEBASTIAN');
INSERT INTO editoriales (nombre,ciudad) VALUES ('EDEBE','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('NORMA EDITORIAL','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('MEDIA LIVE','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('LA POESIA SEÑOR HIDALGO','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('IVAM','VALENCIA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('ROBINBOOK','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('FUNDACION SANTA MARIA LA REAL','PALENCIA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('BELACQVA','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('NORDICA','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('PUBLICO','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('LIBRERÍA UNIVERSITARIA','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('DYKINSON','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('SCYLA','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('TIMUN MAS','BARCELON');
INSERT INTO editoriales (nombre,ciudad) VALUES ('NECODISNE','MALAGA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('SAN PABLO','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('KRK','OVIEDO');
INSERT INTO editoriales (nombre,ciudad) VALUES ('NORTESUR','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('LA ESFERA DE LOS LIBROS','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('PAGINAS DE ESPUMA','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('ALMUZARA','CORDOBA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('AEMET','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('MINISTERIO DE MEDIO AMBIENTE','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('DOSDEARTE','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('JUNTA DE ANDALUCIA',null);
INSERT INTO editoriales (nombre,ciudad) VALUES ('CONSORCIO DE LA CIUDAD MONUMENTAL DE MERIDA','MERIDA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('KONEMANN','LONDRES');
INSERT INTO editoriales (nombre,ciudad) VALUES ('CENTRO DE LINGÜÍSTICA APLICADA ATENEA','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('EKSMO','MOSCU');
INSERT INTO editoriales (nombre,ciudad) VALUES ('BACKLIST','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('AKAL','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('LA COMPAÑÍA','BUENOS AIRES');
INSERT INTO editoriales (nombre,ciudad) VALUES ('DISGALIBRO','LA CORUÑA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('PATRINMONIO NACIONAL','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('BLUME','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('PROGRESO','MOSCU');
INSERT INTO editoriales (nombre,ciudad) VALUES ('ALDEASA','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('DIFUSION','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('LA OTRA ORILLLA','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('EDICIONES SINGULARES','SAN LORENZO DEL ESCORIAL');
INSERT INTO editoriales (nombre,ciudad) VALUES ('UNIDAD EDITORIAL','VALLADOLID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('TAURUS','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('HERA','SALAMANCA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('DOSSOLES','BURGOS');
INSERT INTO editoriales (nombre,ciudad) VALUES ('PRE-TEXTOS','VALENCIA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('CLAN','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('RENACIMIENTO','SEVILLA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('EDICIONES HISPANO ESLAVAS','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('ATALANTA','GERONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('AYN EDICIONES','MARID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('MINISTERIO DE CULTURA','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('BAUDELAIRE','PARIS');
INSERT INTO editoriales (nombre,ciudad) VALUES ('HERNANDO','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('EDICIONES BAILE DEL SOL','TENERIFE');
INSERT INTO editoriales (nombre,ciudad) VALUES ('FUNDACION MANUEL RAMOS ANDRADE','SALMANCA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('LENGUA RUSA','MOSCU');
INSERT INTO editoriales (nombre,ciudad) VALUES ('ARTISTA RSFSR','SAN PETERSBURGO');
INSERT INTO editoriales (nombre,ciudad) VALUES ('LA OTRA ORILLA','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('ZLATOUST','SAN PETERSBURGO');
INSERT INTO editoriales (nombre,ciudad) VALUES ('FENIX','ROSTOV DEL DON');
INSERT INTO editoriales (nombre,ciudad) VALUES ('LENISDAT','SAN PETERSBURGO');
INSERT INTO editoriales (nombre,ciudad) VALUES ('AURORA','LENINGRADO');
INSERT INTO editoriales (nombre,ciudad) VALUES ('451 EDITORES','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('LIBROS DEL SILENCIO','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('H F ULLMANN',null);
INSERT INTO editoriales (nombre,ciudad) VALUES ('VERGARA','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('GALAXIA GUTEMBERG','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('GIGAMESH','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('AYUNTAMIENTO DE VALLADOLID','VALLADOLID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('FUNDACION DEL PATRIMONIO HISTORICO DE CASTILLA Y L','VALLADOLID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('PERIFERICA','CACERES');
INSERT INTO editoriales (nombre,ciudad) VALUES ('GALLO NERO',null);
INSERT INTO editoriales (nombre,ciudad) VALUES ('P-2','SAN PETERSBURGO');
INSERT INTO editoriales (nombre,ciudad) VALUES ('ABRIS','SAN PETERSBURGO');
INSERT INTO editoriales (nombre,ciudad) VALUES ('GALERIA ESTATAL TETRIAKOV','MOSCU');
INSERT INTO editoriales (nombre,ciudad) VALUES ('YARKIY GOROD','SAN PETERSBURGO');
INSERT INTO editoriales (nombre,ciudad) VALUES ('IVAN FIODOROV','SAN PETERSBURGO');
INSERT INTO editoriales (nombre,ciudad) VALUES ('TK AKM','SAN PETERSBURGO');
INSERT INTO editoriales (nombre,ciudad) VALUES ('ALFA COLOR','SAN PETERSBURGO');
INSERT INTO editoriales (nombre,ciudad) VALUES ('ART KURIER','MOSCU');
INSERT INTO editoriales (nombre,ciudad) VALUES ('LE MONDE',null);
INSERT INTO editoriales (nombre,ciudad) VALUES ('CASA DEL LIBRO ESLAVO','MOSCU');
INSERT INTO editoriales (nombre,ciudad) VALUES ('VECHE','MOSCU');
INSERT INTO editoriales (nombre,ciudad) VALUES ('CULT INFORM PRENSA','SAN PETERSBURGO');
INSERT INTO editoriales (nombre,ciudad) VALUES ('ASTREL','MOSCU');
INSERT INTO editoriales (nombre,ciudad) VALUES ('LAERTES','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('CIUDAD BRILLANTE','SAN PETERSBURGO');
INSERT INTO editoriales (nombre,ciudad) VALUES ('ARKAIM','VLADIMIR');
INSERT INTO editoriales (nombre,ciudad) VALUES ('OOO AURORA','SAN PETERSBURGO');
INSERT INTO editoriales (nombre,ciudad) VALUES ('IVAN FEDOROV','RUSIA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('SEÑOR PULPO','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('VISION NET','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('JORGE SAN ROMANVILLALON',null);
INSERT INTO editoriales (nombre,ciudad) VALUES ('AYUNTAMIENTO DE FRIAS','BURGOS');
INSERT INTO editoriales (nombre,ciudad) VALUES ('EDILUPA',null);
INSERT INTO editoriales (nombre,ciudad) VALUES ('SAN ESTEBAN','SALAMANCA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('LIBROS CUPULA','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('AUTOMATICA','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('GADIR','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('REINO DECORDELIA','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('LA CUPULA','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('PASADO Y PRESENTE','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('TF EDITORES','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('ANTONIO PAREJA','TOLEDO');
INSERT INTO editoriales (nombre,ciudad) VALUES ('JULIO DE LA CRUZ','TOLEDO');
INSERT INTO editoriales (nombre,ciudad) VALUES ('JEAN HENRI PASSINI','TOLEDO');
INSERT INTO editoriales (nombre,ciudad) VALUES ('CONVENTO SAN JUAN DE LOS REYES','TOLEDO');
INSERT INTO editoriales (nombre,ciudad) VALUES ('MINISTERIO DE DEFENSA','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('LIBROS DEL KO','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('FUNDAMENTOS','CARACAS');
INSERT INTO editoriales (nombre,ciudad) VALUES ('CAPITAN SWING','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('CUADERNOS DEL VIGIA','GRANADA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('ECC EDICIONES','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('MIRAGUANO EDICIONES','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('ECOS',null);
INSERT INTO editoriales (nombre,ciudad) VALUES ('TRAVELBUG','SAN DEBASTIAN');
INSERT INTO editoriales (nombre,ciudad) VALUES ('ASTIBERRI','BILBAO');
INSERT INTO editoriales (nombre,ciudad) VALUES ('GYPAETE','PAU');
INSERT INTO editoriales (nombre,ciudad) VALUES ('PIRINEO','HUESCA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('DDPCB','HUESCA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('VESTIGIUM','ZARAGOZA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('CAI','ZARAGOZA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('DIPUTACION DE HUESCA','HUESCA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('EDITUR',null);
INSERT INTO editoriales (nombre,ciudad) VALUES ('PHOTOSFERA',null);
INSERT INTO editoriales (nombre,ciudad) VALUES ('PRAMES','ZARAGOZA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('LLIBRES DE MATRICULA',null);
INSERT INTO editoriales (nombre,ciudad) VALUES ('EDICIONES SICILIA',null);
INSERT INTO editoriales (nombre,ciudad) VALUES ('CORNER','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('FUNDACION LAS EDADES DEL HOMBRE',null);
INSERT INTO editoriales (nombre,ciudad) VALUES ('JANES EDITOR','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('EDICIONES PAULINAS','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('AYUNTAMIENTO DE BARCELONA','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('MASCARON','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('ALZAMORA ARTGRAFICA',null);
INSERT INTO editoriales (nombre,ciudad) VALUES ('VERDAD','MOSCU');
INSERT INTO editoriales (nombre,ciudad) VALUES ('LITERATO CONTEMPORANEO','MINSK');
INSERT INTO editoriales (nombre,ciudad) VALUES ('INSTRUCCIÓN','MOSCU');
INSERT INTO editoriales (nombre,ciudad) VALUES ('LOGUEZ','SALAMANCA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('INGO MUSICA','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('VISOR','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('CAPITAN SWING / NORDICA','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('MUSEO ORIENTAL','VALLADOLID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('SATORI','GIJON');
INSERT INTO editoriales (nombre,ciudad) VALUES ('ALFABIA','BARCELONA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('ENEIDA','MADRID');
INSERT INTO editoriales (nombre,ciudad) VALUES ('DELIRIO','SALAMANCA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('UNIVERSIDAD DE ALCALA','ALCALA DE HENARES');
INSERT INTO editoriales (nombre,ciudad) VALUES ('ESPINO ALBAR','PONTEDEUME');
INSERT INTO editoriales (nombre,ciudad) VALUES ('BATISCAFO',null);
INSERT INTO editoriales (nombre,ciudad) VALUES ('PILI DOMINGUEZ / LOLI IBAÑEZ','SOS');
INSERT INTO editoriales (nombre,ciudad) VALUES ('JOAQUIN GUERRERO CAMPO','AINSA');
INSERT INTO editoriales (nombre,ciudad) VALUES ('LIBRALIA','VALLADOLID');
