INSERT INTO colecciones (nombre, editorial) VALUES ('NOVELA HISTORICA',9);
INSERT INTO colecciones (nombre, editorial) VALUES ('ULTIMOS EXITOS DE LA NOVELA HISTORICA',26);
INSERT INTO colecciones (nombre, editorial) VALUES ('EL EGIPTO DE ELOS FARAONES',26);
INSERT INTO colecciones (nombre, editorial) VALUES ('LO MEJOR DE LA NUEVA NOVELA HISTORICA',26);
INSERT INTO colecciones (nombre, editorial) VALUES ('LAS AVENTURAS DEL CAPITAN ALATRISTE',44);
INSERT INTO colecciones (nombre, editorial) VALUES ('LAS MEJORES NOVELAS EN CASTELLANO DEL SIGLO XX',123);
INSERT INTO colecciones (nombre, editorial) VALUES ('NARRATIVA ACTUAL',34);
INSERT INTO colecciones (nombre, editorial) VALUES ('NUEVA NARRATIVA',34);
INSERT INTO colecciones (nombre, editorial) VALUES ('ANDANZAS',15);
INSERT INTO colecciones (nombre, editorial) VALUES ('NARRATIVA',19);
INSERT INTO colecciones (nombre, editorial) VALUES ('ALBA CLASICA',1);
INSERT INTO colecciones (nombre, editorial) VALUES ('OBRAS MAESTRAS DE LA LITERATURA CONTEMPORANEA',57);
INSERT INTO colecciones (nombre, editorial) VALUES ('GRANDES GENIOS DE LA LITERATURA UNIVERSAL',42);
INSERT INTO colecciones (nombre, editorial) VALUES ('ALBA CLASICA MAIOR',1);
INSERT INTO colecciones (nombre, editorial) VALUES ('PUNTO DE LECTURA',11);
INSERT INTO colecciones (nombre, editorial) VALUES ('GRANDES OBRAS',102);
INSERT INTO colecciones (nombre, editorial) VALUES ('GRANDES CLASICOS',1);
INSERT INTO colecciones (nombre, editorial) VALUES ('GRANDES MAESTROS DEL CRIMEN Y MISTERIO',20);
INSERT INTO colecciones (nombre, editorial) VALUES ('BACKLIST',26);
INSERT INTO colecciones (nombre, editorial) VALUES ('BOOKET',26);
INSERT INTO colecciones (nombre, editorial) VALUES ('CLASICOS LITERATURA',370);
INSERT INTO colecciones (nombre, editorial) VALUES ('BIBLIOTECA BASICA',39);
INSERT INTO colecciones (nombre, editorial) VALUES ('GRANDES NOVELAS DE AMOR DE LA LITERATURA UNIVERSAL',26);
INSERT INTO colecciones (nombre, editorial) VALUES ('ALTAIR VIAJES',48);
INSERT INTO colecciones (nombre, editorial) VALUES ('MUSEOS DEL MUNDO',19);
INSERT INTO colecciones (nombre, editorial) VALUES ('BESTSELLERS',9);
INSERT INTO colecciones (nombre, editorial) VALUES ('EL LIBRO DE BOLSILLO ALIANZA EDITORIAL',13);
INSERT INTO colecciones (nombre, editorial) VALUES ('COMPACTOS',22);
INSERT INTO colecciones (nombre, editorial) VALUES ('BIBLIOTECA DE AUTOR',20);
INSERT INTO colecciones (nombre, editorial) VALUES ('GRANDES VIAJEROS',7);
INSERT INTO colecciones (nombre, editorial) VALUES ('GRANDES AUTORES VALENCIANOS',129);
INSERT INTO colecciones (nombre, editorial) VALUES ('AUTORES ESPAÑOLES E IBERICOA MERICANOS',26);
INSERT INTO colecciones (nombre, editorial) VALUES ('CLASICOS DEL SIGLO XX',34);
INSERT INTO colecciones (nombre, editorial) VALUES ('BOLSILLO',19);
INSERT INTO colecciones (nombre, editorial) VALUES ('BIBLIOTECA BREVE',57);
INSERT INTO colecciones (nombre, editorial) VALUES ('NARRATIVAS HISPANICAS',22);
INSERT INTO colecciones (nombre, editorial) VALUES ('PANORAMA DE NARRATIVAS',22);
INSERT INTO colecciones (nombre, editorial) VALUES (' N',13);
INSERT INTO colecciones (nombre, editorial) VALUES ('ESPAÑA ESCRITA',26);
INSERT INTO colecciones (nombre, editorial) VALUES ('MEMORIA CRITICA',27);
INSERT INTO colecciones (nombre, editorial) VALUES ('CLASICOS CONTEMPORANEOS INTERNACIONALES',26);
INSERT INTO colecciones (nombre, editorial) VALUES ('NARRATIVA',4);
INSERT INTO colecciones (nombre, editorial) VALUES ('MODERNOS Y CLASICOS',53);
INSERT INTO colecciones (nombre, editorial) VALUES ('NARRATIVA EN ESPAÑOL',157);
INSERT INTO colecciones (nombre, editorial) VALUES ('MAXI TUSQUETS',15);
INSERT INTO colecciones (nombre, editorial) VALUES ('BOLSILLO',157);
INSERT INTO colecciones (nombre, editorial) VALUES ('NOVELA NEGRA ACTUAL',26);
INSERT INTO colecciones (nombre, editorial) VALUES ('HOY LIBRO',22);
INSERT INTO colecciones (nombre, editorial) VALUES ('QUINTETO',49);
INSERT INTO colecciones (nombre, editorial) VALUES ('BIBIOTECA EDUARDO MENDOZA',57);
INSERT INTO colecciones (nombre, editorial) VALUES ('BIBLIOTECA FORMENTOR',57);
INSERT INTO colecciones (nombre, editorial) VALUES ('CUENTOS DE NAVIDAD',127);
INSERT INTO colecciones (nombre, editorial) VALUES ('AUTORES DE LENGUA ESPAÑOLA',34);
INSERT INTO colecciones (nombre, editorial) VALUES ('BIBLIOTECA CARVALHO',26);
INSERT INTO colecciones (nombre, editorial) VALUES ('BASICOS 2002',140);
INSERT INTO colecciones (nombre, editorial) VALUES ('BOOKET',null);
INSERT INTO colecciones (nombre, editorial) VALUES ('DEBOLSILLO',null);
INSERT INTO colecciones (nombre, editorial) VALUES ('NARRADORES DE HOY',35);
INSERT INTO colecciones (nombre, editorial) VALUES ('LITERARIA',5);
INSERT INTO colecciones (nombre, editorial) VALUES ('BIBLIOTECA DE',5);
INSERT INTO colecciones (nombre, editorial) VALUES ('BIBLIOTECA DE',7);
INSERT INTO colecciones (nombre, editorial) VALUES ('DESTINOLIBRO',32);
INSERT INTO colecciones (nombre, editorial) VALUES ('MAR ADENTRO',113);
INSERT INTO colecciones (nombre, editorial) VALUES ('MITOS',37);
INSERT INTO colecciones (nombre, editorial) VALUES ('LETRAS DE BOLSILLO',65);
INSERT INTO colecciones (nombre, editorial) VALUES ('JET',5);
INSERT INTO colecciones (nombre, editorial) VALUES ('RELATOS',5);
INSERT INTO colecciones (nombre, editorial) VALUES ('RELATOS BREVES',9);
INSERT INTO colecciones (nombre, editorial) VALUES ('OBRAS MAESTRAS DE LA LITERATURA UNIVERSAL',89);
INSERT INTO colecciones (nombre, editorial) VALUES ('CLASICOS ESPAÑOLES',9);
INSERT INTO colecciones (nombre, editorial) VALUES ('LOS LIBROS DE LA CANDAMIA',126);
INSERT INTO colecciones (nombre, editorial) VALUES ('CASTALIAPRIMA',137);
INSERT INTO colecciones (nombre, editorial) VALUES ('PALABRA EN EL TIEMPO',4);
INSERT INTO colecciones (nombre, editorial) VALUES ('LAS MILY UNA VOCES',37);
INSERT INTO colecciones (nombre, editorial) VALUES ('NARRATIVAS HISTORICAS',49);
INSERT INTO colecciones (nombre, editorial) VALUES ('BIBLIOTECA DE',37);
INSERT INTO colecciones (nombre, editorial) VALUES ('GOTICA',79);
INSERT INTO colecciones (nombre, editorial) VALUES ('EL CLUB DIOGENES',79);
INSERT INTO colecciones (nombre, editorial) VALUES ('FABULA',15);
INSERT INTO colecciones (nombre, editorial) VALUES ('PREMIO CERVANTES',62);
INSERT INTO colecciones (nombre, editorial) VALUES ('LITERATURA',20);
INSERT INTO colecciones (nombre, editorial) VALUES ('BOLSILLO',51);
INSERT INTO colecciones (nombre, editorial) VALUES ('HISTORICA',144);
INSERT INTO colecciones (nombre, editorial) VALUES ('ALFANHUI',96);
INSERT INTO colecciones (nombre, editorial) VALUES ('CLASICOS JOVENES',78);
INSERT INTO colecciones (nombre, editorial) VALUES ('CLASICOS UNIVERSALES SM',12);
INSERT INTO colecciones (nombre, editorial) VALUES ('TUS LIBROS',2);
INSERT INTO colecciones (nombre, editorial) VALUES ('NOVELAS INMORTALES',104);
INSERT INTO colecciones (nombre, editorial) VALUES ('HISTORIAS DE SIEMPRE',44);
INSERT INTO colecciones (nombre, editorial) VALUES ('SERIE AVENTURA',28);
INSERT INTO colecciones (nombre, editorial) VALUES ('EL BAUL DE LOS CUENTOS',7);
INSERT INTO colecciones (nombre, editorial) VALUES ('CAJON DE CUENTOS',46);
INSERT INTO colecciones (nombre, editorial) VALUES ('LA FORALADA',154);
INSERT INTO colecciones (nombre, editorial) VALUES ('BIBLIOTECA DE CUENTOS MARAVILLOSOS',63);
INSERT INTO colecciones (nombre, editorial) VALUES ('NUEVO AURIGA',3);
INSERT INTO colecciones (nombre, editorial) VALUES ('GRANDES AUTORES',4);
INSERT INTO colecciones (nombre, editorial) VALUES ('TEMAS LOCALES',121);
INSERT INTO colecciones (nombre, editorial) VALUES ('LA EDAD DE ORO',51);
INSERT INTO colecciones (nombre, editorial) VALUES ('LA ESCRITURA DESATADA',7);
INSERT INTO colecciones (nombre, editorial) VALUES ('BIBLIOTECA HISPANIA ILUSTRADA',6);
INSERT INTO colecciones (nombre, editorial) VALUES ('VIOLETA',28);
INSERT INTO colecciones (nombre, editorial) VALUES ('FEMENINO',4);
INSERT INTO colecciones (nombre, editorial) VALUES ('CUADRADA',17);
INSERT INTO colecciones (nombre, editorial) VALUES ('LAS GUIAS DEL DUERO',208);
INSERT INTO colecciones (nombre, editorial) VALUES ('TEXTOS DE ESCRITOR',44);
INSERT INTO colecciones (nombre, editorial) VALUES ('CLASICOS DEL SIGLO XX',9);
INSERT INTO colecciones (nombre, editorial) VALUES ('NOVELA HISTORICA DE CRIMEN Y MISTERIO',114);
INSERT INTO colecciones (nombre, editorial) VALUES ('EL LIBRO DE BOLSILLO',13);
INSERT INTO colecciones (nombre, editorial) VALUES ('BOLSILLO JUVENIL',4);
INSERT INTO colecciones (nombre, editorial) VALUES ('ANCORA Y DELFIN',32);
INSERT INTO colecciones (nombre, editorial) VALUES ('SELECCIONES DE BIBLIOTECA ORO',28);
INSERT INTO colecciones (nombre, editorial) VALUES ('MOBY DICK BIBLIOTECA DE BOLSILLO JUNIOR',103);
INSERT INTO colecciones (nombre, editorial) VALUES ('RENO',33);
INSERT INTO colecciones (nombre, editorial) VALUES ('CLASICOS DEL MUNDO',24);
INSERT INTO colecciones (nombre, editorial) VALUES ('NOVELAS Y CUENTOS',43);
INSERT INTO colecciones (nombre, editorial) VALUES ('ERASMO',61);
INSERT INTO colecciones (nombre, editorial) VALUES ('BOLSILLO',73);
INSERT INTO colecciones (nombre, editorial) VALUES ('QUINTETO',65);
INSERT INTO colecciones (nombre, editorial) VALUES ('POCKET',49);
INSERT INTO colecciones (nombre, editorial) VALUES ('BOLSILLO /ALFAGUARA',44);
INSERT INTO colecciones (nombre, editorial) VALUES ('LITERATURA UNIVERSAL',35);
INSERT INTO colecciones (nombre, editorial) VALUES ('CLASICOS PLAZA Y JANES',5);
INSERT INTO colecciones (nombre, editorial) VALUES ('LITERATURA CONTEMPORANEA',57);
INSERT INTO colecciones (nombre, editorial) VALUES ('POPULAR',26);
INSERT INTO colecciones (nombre, editorial) VALUES ('BIBLIOTECA POPULAR RTVE',26);
INSERT INTO colecciones (nombre, editorial) VALUES ('BIBLIOTACA GENERAL',39);
INSERT INTO colecciones (nombre, editorial) VALUES ('COLECCIÓN DE POESIA',9);
INSERT INTO colecciones (nombre, editorial) VALUES ('LETRAS HISPANICAS',10);
INSERT INTO colecciones (nombre, editorial) VALUES ('BIBLIOTECA ANDALUZA',149);
INSERT INTO colecciones (nombre, editorial) VALUES ('LA SONRISA VERTICAL',15);
INSERT INTO colecciones (nombre, editorial) VALUES ('BIBLIOTECA DEL SOL',135);
INSERT INTO colecciones (nombre, editorial) VALUES ('VENUS',68);
INSERT INTO colecciones (nombre, editorial) VALUES ('OPUS VOLUPTATIS',176);
INSERT INTO colecciones (nombre, editorial) VALUES ('CLASICOS DE SIEMPRE',94);
INSERT INTO colecciones (nombre, editorial) VALUES ('VERBIGRACIA',124);
INSERT INTO colecciones (nombre, editorial) VALUES ('LIBROS DEL BUEN HUMOR',124);
INSERT INTO colecciones (nombre, editorial) VALUES ('LIBRO AMIGO',35);
INSERT INTO colecciones (nombre, editorial) VALUES ('LIBROS DB',138);
INSERT INTO colecciones (nombre, editorial) VALUES ('BIBLIOTECA CLASICA Y CONTEMPORANEA',97);
INSERT INTO colecciones (nombre, editorial) VALUES ('NARRATIVAS CONTEMPORANEAS',49);
INSERT INTO colecciones (nombre, editorial) VALUES ('BOLSILLO',75);
INSERT INTO colecciones (nombre, editorial) VALUES ('PUNTO OMEGA',76);
INSERT INTO colecciones (nombre, editorial) VALUES ('SE HACE CAMINO AL ANDAR',58);
INSERT INTO colecciones (nombre, editorial) VALUES ('LIBROS DE BOLSILLO',64);
INSERT INTO colecciones (nombre, editorial) VALUES ('PALABRA MENOR',4);
INSERT INTO colecciones (nombre, editorial) VALUES ('BIBLIOTECA UNIVERSAL',71);
INSERT INTO colecciones (nombre, editorial) VALUES ('AUSTRAL',19);
INSERT INTO colecciones (nombre, editorial) VALUES ('EL ARCA DE PAPEL',5);
INSERT INTO colecciones (nombre, editorial) VALUES ('DIVULGACION UNIVERSITARIA',52);
INSERT INTO colecciones (nombre, editorial) VALUES ('PURPURA',107);
INSERT INTO colecciones (nombre, editorial) VALUES ('CLASICOS',137);
INSERT INTO colecciones (nombre, editorial) VALUES ('ROTATIVA',5);
INSERT INTO colecciones (nombre, editorial) VALUES ('NOVELA HISTORICA',39);
INSERT INTO colecciones (nombre, editorial) VALUES ('FICCION INTERNACIONAL',67);
INSERT INTO colecciones (nombre, editorial) VALUES ('PRIMERA PERSONA',2);
INSERT INTO colecciones (nombre, editorial) VALUES ('GRANDES PASIONES DE LA LITERATURA',20);
INSERT INTO colecciones (nombre, editorial) VALUES ('AVE FENIX /SERIE MAYOR',5);
INSERT INTO colecciones (nombre, editorial) VALUES ('GRANDES MUJERES',39);
INSERT INTO colecciones (nombre, editorial) VALUES ('NOVELA HISTORICA',85);
INSERT INTO colecciones (nombre, editorial) VALUES ('MEMORIA',56);
INSERT INTO colecciones (nombre, editorial) VALUES ('LAS TRES EDADES',51);
INSERT INTO colecciones (nombre, editorial) VALUES ('EL OJO DEL TIEMPO',51);
INSERT INTO colecciones (nombre, editorial) VALUES ('AFLUENTES',7);
INSERT INTO colecciones (nombre, editorial) VALUES ('LETRA CELESTE',40);
INSERT INTO colecciones (nombre, editorial) VALUES ('NARRATIVA DEL ACANTILADO',91);
INSERT INTO colecciones (nombre, editorial) VALUES ('CLASICOS DEL BRONCE',69);
INSERT INTO colecciones (nombre, editorial) VALUES ('MUJERES APASIONADAS',26);
INSERT INTO colecciones (nombre, editorial) VALUES ('BEST SELLER',68);
INSERT INTO colecciones (nombre, editorial) VALUES ('BIOGRAFIAS ESPASA',19);
INSERT INTO colecciones (nombre, editorial) VALUES ('SERIE ANA LADE LAS TEJAS VERDES',85);
INSERT INTO colecciones (nombre, editorial) VALUES ('AMBITO CASTILLA Y LEON',131);
INSERT INTO colecciones (nombre, editorial) VALUES ('BYBLOS',7);
INSERT INTO colecciones (nombre, editorial) VALUES ('GUIAS VISUALES',19);
INSERT INTO colecciones (nombre, editorial) VALUES ('BIOGRAFIAS',292);
INSERT INTO colecciones (nombre, editorial) VALUES ('ALIANZA MUSIACA',13);
INSERT INTO colecciones (nombre, editorial) VALUES ('HISTORIA DE LA MUSICA',62);
INSERT INTO colecciones (nombre, editorial) VALUES ('LITERATURA MONDADORI',37);
INSERT INTO colecciones (nombre, editorial) VALUES ('CARAVANSERAI',82);
INSERT INTO colecciones (nombre, editorial) VALUES ('BIBLIOTECA CLASICA',19);
INSERT INTO colecciones (nombre, editorial) VALUES ('LOS LIBROS DE EL ADELANTO',200);
INSERT INTO colecciones (nombre, editorial) VALUES ('NOVELAS EJEMPLARES',136);
INSERT INTO colecciones (nombre, editorial) VALUES ('NARRATIVA DE HOY',34);
INSERT INTO colecciones (nombre, editorial) VALUES ('EL GRAN TEATRO DEL MUNDO',20);
INSERT INTO colecciones (nombre, editorial) VALUES ('LITERATURA ALFAGUARA',44);
INSERT INTO colecciones (nombre, editorial) VALUES ('FABULA',26);
INSERT INTO colecciones (nombre, editorial) VALUES ('PLANETA BOLSILLO',26);
INSERT INTO colecciones (nombre, editorial) VALUES ('BIBLIOTECA PABLO COELHO',26);
INSERT INTO colecciones (nombre, editorial) VALUES ('LOS GRANDES AUTORES DE LA NARRATIVA ACTUAL',26);
INSERT INTO colecciones (nombre, editorial) VALUES ('LOS GRANDES AUTORES DE LA NARRATIVA ESPAÑOL ACTUAL',26);
INSERT INTO colecciones (nombre, editorial) VALUES ('PREMIOS NADAL',26);
INSERT INTO colecciones (nombre, editorial) VALUES ('PREMIO PLANETA',26);
INSERT INTO colecciones (nombre, editorial) VALUES ('BIBLIOTCA UNIVERSAL PLANETA',26);
INSERT INTO colecciones (nombre, editorial) VALUES ('GUIAS DE LA ESPAÑA INSOLITA',155);
INSERT INTO colecciones (nombre, editorial) VALUES ('CLASICOS BABILONIA',95);
INSERT INTO colecciones (nombre, editorial) VALUES ('FONTANA',41);
INSERT INTO colecciones (nombre, editorial) VALUES ('BOLSILLO RBA',34);
INSERT INTO colecciones (nombre, editorial) VALUES ('CUADERNOS INFIMOS',15);
INSERT INTO colecciones (nombre, editorial) VALUES ('EL AVE FENIX',5);
INSERT INTO colecciones (nombre, editorial) VALUES ('GRAN RENO',5);
INSERT INTO colecciones (nombre, editorial) VALUES ('BIBLIOTECA DE NORA ROBERTS',90);
INSERT INTO colecciones (nombre, editorial) VALUES ('GRANDES EXITOS / GRANDES ESCRITORAS',39);
INSERT INTO colecciones (nombre, editorial) VALUES ('EL LIBRO AGUILAR',72);
INSERT INTO colecciones (nombre, editorial) VALUES ('TEXTOS TIMIDOS',136);
INSERT INTO colecciones (nombre, editorial) VALUES ('ALIANZA CIEN',13);
INSERT INTO colecciones (nombre, editorial) VALUES ('EL LIBRO POSTAL',45);
INSERT INTO colecciones (nombre, editorial) VALUES ('BIBLIOTECA DE LA LITERATURA UNIVERSAL',14);
INSERT INTO colecciones (nombre, editorial) VALUES ('NOSTROMO',17);
INSERT INTO colecciones (nombre, editorial) VALUES ('METATEMAS',15);
INSERT INTO colecciones (nombre, editorial) VALUES ('PENSAMIENTO',87);
INSERT INTO colecciones (nombre, editorial) VALUES ('NUEVA BIBLIOTECA',150);
INSERT INTO colecciones (nombre, editorial) VALUES ('REFERENCIAS',84);
INSERT INTO colecciones (nombre, editorial) VALUES ('EDICIONES DE BOLSILLO',4);
INSERT INTO colecciones (nombre, editorial) VALUES ('GUERNICA',58);
INSERT INTO colecciones (nombre, editorial) VALUES ('CLASICOS UNIVERSALES PLANETA',26);
INSERT INTO colecciones (nombre, editorial) VALUES ('ECONOMICA',152);
INSERT INTO colecciones (nombre, editorial) VALUES ('BIBLIOTECA DE BOLSILLO DE EDICIONES IBERICAS',99);
INSERT INTO colecciones (nombre, editorial) VALUES ('BIBLIOTECA DE BOLSILLO DE MIÑON',119);
INSERT INTO colecciones (nombre, editorial) VALUES ('BIBLIOTECA IV CENTENARIO',133);
INSERT INTO colecciones (nombre, editorial) VALUES ('AGUILAR MAIOR',72);
INSERT INTO colecciones (nombre, editorial) VALUES ('NARRATIVA DEL SIGLO XX EN LENGUIA CASTELLANA',19);
INSERT INTO colecciones (nombre, editorial) VALUES ('NUEVA NARRATIVA ESPAÑOLA',148);
INSERT INTO colecciones (nombre, editorial) VALUES ('PUNTO OMEGA',76);
INSERT INTO colecciones (nombre, editorial) VALUES ('25 ANNIVERSARY',283);
INSERT INTO colecciones (nombre, editorial) VALUES ('GRANDES FOTOGRAFOS MAGNUM PHOTOS',39);
INSERT INTO colecciones (nombre, editorial) VALUES ('LA MIRADA DEL TIEMPO',9);
INSERT INTO colecciones (nombre, editorial) VALUES ('LOS LIBROS DE SIETE LEGUAS',55);
INSERT INTO colecciones (nombre, editorial) VALUES ('BIBLIOTECA DEL VIAJEREO ABC',77);
INSERT INTO colecciones (nombre, editorial) VALUES ('NOVELA HISTORICA',384);
INSERT INTO colecciones (nombre, editorial) VALUES ('DESCUBRIR',21);
INSERT INTO colecciones (nombre, editorial) VALUES ('HISTORICA',7);
INSERT INTO colecciones (nombre, editorial) VALUES ('CRONOS',88);
INSERT INTO colecciones (nombre, editorial) VALUES ('ENSAYO EDHASA',49);
INSERT INTO colecciones (nombre, editorial) VALUES ('FORUM',19);
INSERT INTO colecciones (nombre, editorial) VALUES ('TIEMPO DE MEMORIA',15);
INSERT INTO colecciones (nombre, editorial) VALUES ('PUEBLOS',155);
INSERT INTO colecciones (nombre, editorial) VALUES ('BIBLIOTECA EL MUNDO',50);
INSERT INTO colecciones (nombre, editorial) VALUES ('LETRAS UNIVERSALES',10);
INSERT INTO colecciones (nombre, editorial) VALUES ('BIBLIOTECA EDAF',75);
INSERT INTO colecciones (nombre, editorial) VALUES ('CUADERNOS DEL ACANTILADO',91);
INSERT INTO colecciones (nombre, editorial) VALUES ('CLASICOS SELECCIÓN',47);
INSERT INTO colecciones (nombre, editorial) VALUES ('GALERIA LITERARIA',64);
INSERT INTO colecciones (nombre, editorial) VALUES ('HISTORIA UNIVERSAL DE LA LITERARATURA',20);
INSERT INTO colecciones (nombre, editorial) VALUES ('GRANDES ESCRITORES',114);
INSERT INTO colecciones (nombre, editorial) VALUES ('BIBLIOTECA FUNDAMENTAL DE NUESTRO TIEMPO',13);
INSERT INTO colecciones (nombre, editorial) VALUES ('TEXTOS CLASICOS ANOTADOS',36);
INSERT INTO colecciones (nombre, editorial) VALUES ('HISTORIA DE ESPAÑA',9);
INSERT INTO colecciones (nombre, editorial) VALUES ('BIBLIOTECA HISTORIA DE ESPAÑA',34);
INSERT INTO colecciones (nombre, editorial) VALUES ('GRANDES BIOGRAFIAS DE LA HISTORIA DE ESPAÑA',26);
INSERT INTO colecciones (nombre, editorial) VALUES ('HISTORIA DE ESPAÑA ALFAGUARA',13);
INSERT INTO colecciones (nombre, editorial) VALUES ('EL ALBIR UNIVERSAL',360);
INSERT INTO colecciones (nombre, editorial) VALUES ('HISTORIA UNIVERSAL SIGLO XXI',355);
INSERT INTO colecciones (nombre, editorial) VALUES ('HISTORIA DE EUROPA SIGLO XXI',355);
INSERT INTO colecciones (nombre, editorial) VALUES ('HISTORIA DE LOS MOVIMIENTOS SOCIALES',355);
INSERT INTO colecciones (nombre, editorial) VALUES ('OBRAS BASICAS DE FORMACION CULTURAL',273);
INSERT INTO colecciones (nombre, editorial) VALUES ('TEMAS CLAVE',39);
INSERT INTO colecciones (nombre, editorial) VALUES ('AGUILAR UNIVERSAL',72);
INSERT INTO colecciones (nombre, editorial) VALUES ('BIBLIOTECA TEMATICA ALIANZA',167);
INSERT INTO colecciones (nombre, editorial) VALUES ('HISTORIA',357);
INSERT INTO colecciones (nombre, editorial) VALUES ('GRANDES OBRAS DE LA CULTURA',34);
INSERT INTO colecciones (nombre, editorial) VALUES ('ALIANZA UNIVERSIDAD',13);
INSERT INTO colecciones (nombre, editorial) VALUES ('HISTORIA SERTIE MENOR',10);
INSERT INTO colecciones (nombre, editorial) VALUES ('OBRAS DE HISTORIA',361);
INSERT INTO colecciones (nombre, editorial) VALUES ('NUEVA CLIO',110);
INSERT INTO colecciones (nombre, editorial) VALUES ('BIBLIOTECA PARA EL HOMBRE ACTUAL',76);
INSERT INTO colecciones (nombre, editorial) VALUES ('SERIE DOCUMENTOS',228);
INSERT INTO colecciones (nombre, editorial) VALUES ('HISTORIA ECONOMICA MUNDIAL',355);
INSERT INTO colecciones (nombre, editorial) VALUES ('BIBLIOTECA DE LA HISTORIA',104);
INSERT INTO colecciones (nombre, editorial) VALUES ('BIBLIOTECA DE LA REVISTA DE OCCIDENTE',356);
INSERT INTO colecciones (nombre, editorial) VALUES ('ARIEL HISTORIA',155);
INSERT INTO colecciones (nombre, editorial) VALUES ('ATLAS',351);
INSERT INTO colecciones (nombre, editorial) VALUES ('BIBLIOTECA HISTORIA 16',300);
INSERT INTO colecciones (nombre, editorial) VALUES ('LIBROS DE CORDEL',346);
INSERT INTO colecciones (nombre, editorial) VALUES ('ARIEL QUINCENAL',155);
INSERT INTO colecciones (nombre, editorial) VALUES ('FUNDAMENTOS',359);
INSERT INTO colecciones (nombre, editorial) VALUES ('TEMAS NT',362);
INSERT INTO colecciones (nombre, editorial) VALUES ('CAMINO DE SANTIAGO VIA DE LA PLATA',205);
INSERT INTO colecciones (nombre, editorial) VALUES ('GEO PLANETA',26);
INSERT INTO colecciones (nombre, editorial) VALUES ('GRANDES RUTAS',9);
INSERT INTO colecciones (nombre, editorial) VALUES ('RUTAS A PIE',9);
INSERT INTO colecciones (nombre, editorial) VALUES ('GUIA TOTAL',2);
INSERT INTO colecciones (nombre, editorial) VALUES ('GUIAS CON ENCANTO',9);
INSERT INTO colecciones (nombre, editorial) VALUES ('LIMITE VISUAL',209);
INSERT INTO colecciones (nombre, editorial) VALUES ('LAS GUIAS VISUALES DE ESPAÑA',185);
INSERT INTO colecciones (nombre, editorial) VALUES ('GUIAS VERDES',221);
INSERT INTO colecciones (nombre, editorial) VALUES ('GUIA VIAJAR',157);
INSERT INTO colecciones (nombre, editorial) VALUES ('LAROUSSE DEL VIAJERO',216);
INSERT INTO colecciones (nombre, editorial) VALUES ('TOUR DU MONDE',223);
INSERT INTO colecciones (nombre, editorial) VALUES ('LAS CIUDADES',32);
INSERT INTO colecciones (nombre, editorial) VALUES ('GUIA LONELY PLANET',214);
INSERT INTO colecciones (nombre, editorial) VALUES ('ENCYCLOPOCHE',216);
INSERT INTO colecciones (nombre, editorial) VALUES ('LECTURAS EVEREST 2000',16);
INSERT INTO colecciones (nombre, editorial) VALUES ('LA GUIA VERDE',210);
INSERT INTO colecciones (nombre, editorial) VALUES ('GUIAS ACENTO',212);
INSERT INTO colecciones (nombre, editorial) VALUES ('GUIAS VISUALES',9);
INSERT INTO colecciones (nombre, editorial) VALUES ('GRAN TURISMO',39);
INSERT INTO colecciones (nombre, editorial) VALUES ('GUIAS AUDI',246);
INSERT INTO colecciones (nombre, editorial) VALUES ('MANUALES PRACTICOS PLANETA',26);
INSERT INTO colecciones (nombre, editorial) VALUES ('PLANETA TESTIMONIO',26);
INSERT INTO colecciones (nombre, editorial) VALUES ('DYNAMIS',172);
INSERT INTO colecciones (nombre, editorial) VALUES ('BIBLIOTECA BASICA DEL CREYENTE',142);
INSERT INTO colecciones (nombre, editorial) VALUES ('EL POZO DE SIQUEM',171);
INSERT INTO colecciones (nombre, editorial) VALUES ('ENSAYOSEIX BARRAL',57);
INSERT INTO colecciones (nombre, editorial) VALUES ('PAIDOS STUDIO',271);
INSERT INTO colecciones (nombre, editorial) VALUES ('BIBLIOTECA DE DIVULGACION S/F',161);
INSERT INTO colecciones (nombre, editorial) VALUES ('DOCUMENTO',26);
INSERT INTO colecciones (nombre, editorial) VALUES ('BIBLIOTECA DE DIVULGACION CIENTIFICA',20);
INSERT INTO colecciones (nombre, editorial) VALUES ('EL MEDIO',27);
INSERT INTO colecciones (nombre, editorial) VALUES ('HISTORIA DEL ARTE',9);
INSERT INTO colecciones (nombre, editorial) VALUES ('LOS GENIOS UNIVERSALES DE LA PINTURA',299);
INSERT INTO colecciones (nombre, editorial) VALUES ('LA ERA DE LOS IMPRESIONISTAS',289);
INSERT INTO colecciones (nombre, editorial) VALUES ('ATLAS CULTURALES DEL MUNDO',77);
INSERT INTO colecciones (nombre, editorial) VALUES ('LOS GENIOS DE LA PINTURA ESPAÑOLA',104);
INSERT INTO colecciones (nombre, editorial) VALUES ('DESCUBRA ESPAÑA',62);
INSERT INTO colecciones (nombre, editorial) VALUES ('GRANDES TEMAS',10);
INSERT INTO colecciones (nombre, editorial) VALUES ('PAPELES DEL TIEMPO',260);
INSERT INTO colecciones (nombre, editorial) VALUES ('BIBLIOTECA VISUAL',347);
INSERT INTO colecciones (nombre, editorial) VALUES ('NUEVA CIENCIA NUEVA TECNICA',19);
INSERT INTO colecciones (nombre, editorial) VALUES ('GUIA DE LA NATURALEZA',16);
INSERT INTO colecciones (nombre, editorial) VALUES ('ELEMENTOS DE GEOGRAFIA',353);
INSERT INTO colecciones (nombre, editorial) VALUES ('MANUALES UNIVERSITARIOS',338);
INSERT INTO colecciones (nombre, editorial) VALUES ('ELCANO',155);
INSERT INTO colecciones (nombre, editorial) VALUES ('ECUMENE',343);
INSERT INTO colecciones (nombre, editorial) VALUES ('BIBLIOTECA DE GRANDES TEMAS',39);
INSERT INTO colecciones (nombre, editorial) VALUES ('NATURA',351);
INSERT INTO colecciones (nombre, editorial) VALUES ('TEXTOS GER',338);
INSERT INTO colecciones (nombre, editorial) VALUES ('GEOGRAFIA UNIVERSAL SALVAT',39);
INSERT INTO colecciones (nombre, editorial) VALUES ('AEROGUIAS PLANETA',26);
INSERT INTO colecciones (nombre, editorial) VALUES ('CONOCER ESPAÑA',246);
INSERT INTO colecciones (nombre, editorial) VALUES ('IBERICA',16);
INSERT INTO colecciones (nombre, editorial) VALUES ('GUIAS',257);
INSERT INTO colecciones (nombre, editorial) VALUES ('GALICIA ENTERA',256);
INSERT INTO colecciones (nombre, editorial) VALUES ('PUEBLOS DE GALICIA',227);
INSERT INTO colecciones (nombre, editorial) VALUES ('EL VIAJERO INDEPENDIENTE',248);
INSERT INTO colecciones (nombre, editorial) VALUES ('SERIE PIRENAICA',249);
INSERT INTO colecciones (nombre, editorial) VALUES ('NUESTRAS CIUDADES',32);
INSERT INTO colecciones (nombre, editorial) VALUES ('VIVE Y DESCUBRE',16);
INSERT INTO colecciones (nombre, editorial) VALUES ('GUIAS EVEREST',16);
INSERT INTO colecciones (nombre, editorial) VALUES ('BIBLIOTECA BASICA DE MADRID',243);
INSERT INTO colecciones (nombre, editorial) VALUES ('RECUERDA',16);
INSERT INTO colecciones (nombre, editorial) VALUES ('GUIAS EL VIAJERO',9);
INSERT INTO colecciones (nombre, editorial) VALUES ('GUIARAMA',2);
INSERT INTO colecciones (nombre, editorial) VALUES ('NUEVA GUIA',2);
INSERT INTO colecciones (nombre, editorial) VALUES ('NARRATIVAS',113);
INSERT INTO colecciones (nombre, editorial) VALUES ('VIDA Y COSTUMBRES DE LA EDAD MEDIA',25);
INSERT INTO colecciones (nombre, editorial) VALUES ('PEQUEÑAS GUIAS PRACTICAS',2);
INSERT INTO colecciones (nombre, editorial) VALUES ('LAS CLAVES DEL ARTE',155);
INSERT INTO colecciones (nombre, editorial) VALUES ('CASTILLA Y LEON PASO A PASO',131);
INSERT INTO colecciones (nombre, editorial) VALUES ('GUIAS ILUSTRADAS DE ESPAÑA',220);
INSERT INTO colecciones (nombre, editorial) VALUES ('EDILESA GUIAS',126);
INSERT INTO colecciones (nombre, editorial) VALUES ('VAZQUEZ MONTALBAN',386);
INSERT INTO colecciones (nombre, editorial) VALUES ('NATURALEZA Y MEDIO AMBIENTE',109);
INSERT INTO colecciones (nombre, editorial) VALUES ('LA CIUDAD Y LA MEMORIA',193);
INSERT INTO colecciones (nombre, editorial) VALUES ('SERIE ABIERTA',109);
INSERT INTO colecciones (nombre, editorial) VALUES ('PAGINAS DE TRADCION',109);
INSERT INTO colecciones (nombre, editorial) VALUES ('SALINA BOLSILLO',109);
INSERT INTO colecciones (nombre, editorial) VALUES ('CUADERNOS',350);
INSERT INTO colecciones (nombre, editorial) VALUES ('GUIAS DE LA NATURALEZA',70);
INSERT INTO colecciones (nombre, editorial) VALUES ('CUADERNOS PARA EL FOMENTO DE LA LECTURA',117);
INSERT INTO colecciones (nombre, editorial) VALUES ('BIBLIOTECA DEL LIBRO',117);
INSERT INTO colecciones (nombre, editorial) VALUES ('JUEGOS DE INTELIGENCIA',176);
INSERT INTO colecciones (nombre, editorial) VALUES ('DESAFIOS MATEMATICOS',34);
INSERT INTO colecciones (nombre, editorial) VALUES ('BIBLIOTECA POPULAR',174);
INSERT INTO colecciones (nombre, editorial) VALUES ('DRAKONTOS',27);
INSERT INTO colecciones (nombre, editorial) VALUES ('TERRITORIO PERSONAL',120);
INSERT INTO colecciones (nombre, editorial) VALUES ('GRANDES DIRECTORES',9);
INSERT INTO colecciones (nombre, editorial) VALUES ('EL HOMBRE EN SU MUNDO',148);
INSERT INTO colecciones (nombre, editorial) VALUES ('IMAGO MUNDI',32);
INSERT INTO colecciones (nombre, editorial) VALUES ('COCINA PAIS POR PAIS',9);
INSERT INTO colecciones (nombre, editorial) VALUES ('COCINA DEL PAIS',9);
INSERT INTO colecciones (nombre, editorial) VALUES ('DELICIAS DE COCINA',232);
INSERT INTO colecciones (nombre, editorial) VALUES ('BIOBLIOTECA ESPIRAL',13);
INSERT INTO colecciones (nombre, editorial) VALUES ('LOS LIBROS DE MUCHO GUSTO',316);
INSERT INTO colecciones (nombre, editorial) VALUES ('BIBLIOTECA ANAGRAMA',34);
INSERT INTO colecciones (nombre, editorial) VALUES ('BIBLIOTECA ISABEL ALLENDE',26);
INSERT INTO colecciones (nombre, editorial) VALUES ('HISTORIA DEL ARTE',300);
INSERT INTO colecciones (nombre, editorial) VALUES ('TESOROS DE ESPAÑA',19);
INSERT INTO colecciones (nombre, editorial) VALUES ('DICCIONARIOS RIODUERO',352);
INSERT INTO colecciones (nombre, editorial) VALUES ('BIBLIOTECA DE CONSULTA LAROUSSE',34);
INSERT INTO colecciones (nombre, editorial) VALUES ('SERIE NEGRA',9);
INSERT INTO colecciones (nombre, editorial) VALUES ('EL PAIS AVENTURAS',9);
INSERT INTO colecciones (nombre, editorial) VALUES ('COCINA CON FIRMA',9);
INSERT INTO colecciones (nombre, editorial) VALUES ('TODO PARA LA CASA',9);
INSERT INTO colecciones (nombre, editorial) VALUES ('GUIAS PRACTICAS',2);
INSERT INTO colecciones (nombre, editorial) VALUES ('MANUAL AVANZADO',2);
INSERT INTO colecciones (nombre, editorial) VALUES ('EL LIBRO DE',2);
INSERT INTO colecciones (nombre, editorial) VALUES ('LUXURY GOLD COLLECTION',374);
INSERT INTO colecciones (nombre, editorial) VALUES ('PENDONES DEL HUMOR',374);
INSERT INTO colecciones (nombre, editorial) VALUES ('JUVENIL ALFAGUARA',44);
INSERT INTO colecciones (nombre, editorial) VALUES ('LOS INEDITOS DEL JUEVES',374);
INSERT INTO colecciones (nombre, editorial) VALUES ('CLASICOS EL JUEVES',374);
INSERT INTO colecciones (nombre, editorial) VALUES ('COLECCIÓN TINTIN',17);
INSERT INTO colecciones (nombre, editorial) VALUES ('EL BARCO DE VAPOR',12);
INSERT INTO colecciones (nombre, editorial) VALUES ('BIBLIOTECA JULIO VERNE',34);
INSERT INTO colecciones (nombre, editorial) VALUES ('BIBLIOTECA CALVINO',51);
INSERT INTO colecciones (nombre, editorial) VALUES ('SELECCIÓN AVENTURA',105);
INSERT INTO colecciones (nombre, editorial) VALUES ('ESPACIO ABIERTO',2);
INSERT INTO colecciones (nombre, editorial) VALUES ('ALANDARA',375);
INSERT INTO colecciones (nombre, editorial) VALUES ('GRAN ANGULAR',12);
INSERT INTO colecciones (nombre, editorial) VALUES ('SERIE ROJA',44);
INSERT INTO colecciones (nombre, editorial) VALUES ('CLASICOS ADAPTADOS',343);
INSERT INTO colecciones (nombre, editorial) VALUES ('SUPER CLUB JUVENIL',376);
INSERT INTO colecciones (nombre, editorial) VALUES ('MONTAÑA ENCANTADA',16);
INSERT INTO colecciones (nombre, editorial) VALUES ('ESPASA JUNENIL',19);
INSERT INTO colecciones (nombre, editorial) VALUES ('PROXIMA PARADA',44);
INSERT INTO colecciones (nombre, editorial) VALUES ('SOPA DE LIBROS',2);
INSERT INTO colecciones (nombre, editorial) VALUES ('PERISCOPIO',377);
INSERT INTO colecciones (nombre, editorial) VALUES ('EL NAVEGANTE',12);
INSERT INTO colecciones (nombre, editorial) VALUES ('BIBLIOTECA DIDACTICA ANAYA',2);
INSERT INTO colecciones (nombre, editorial) VALUES ('NOVELA NEGRA',157);
INSERT INTO colecciones (nombre, editorial) VALUES ('HISTORIA UNIVERSAL',9);
INSERT INTO colecciones (nombre, editorial) VALUES ('JORGE LUIS BORGES BIBLIOTECA PERSONAL',20);
INSERT INTO colecciones (nombre, editorial) VALUES ('HISTORIA DE LA LITERATURA ESPAÑOLA',20);
INSERT INTO colecciones (nombre, editorial) VALUES ('CAMILO JOSE CELA OBRAS COMPLETAS',32);
INSERT INTO colecciones (nombre, editorial) VALUES ('GRANDES EXITOS PLANETA',26);
INSERT INTO colecciones (nombre, editorial) VALUES ('CRONICAS DE PRYDAIN',44);
INSERT INTO colecciones (nombre, editorial) VALUES ('MINIGUIA',28);
INSERT INTO colecciones (nombre, editorial) VALUES ('GRAN ENCICLOPEDIA DE BOLSILLO',28);
INSERT INTO colecciones (nombre, editorial) VALUES ('VERTICALES DE BOLSILLO',378);
INSERT INTO colecciones (nombre, editorial) VALUES ('MA NON TROPPO',382);
INSERT INTO colecciones (nombre, editorial) VALUES ('BIBLIOTECA DE AMERICA',188);
INSERT INTO colecciones (nombre, editorial) VALUES ('GUIAS DE CONVERSACION HABLAR EN QUINCE DIAS',387);
INSERT INTO colecciones (nombre, editorial) VALUES ('BIBLIOTECA DE ANA MARIA MOIX',157);
INSERT INTO colecciones (nombre, editorial) VALUES ('CLASICOS DE LA NOVELA POLICIACA',34);
INSERT INTO colecciones (nombre, editorial) VALUES ('ATLAS ILUSTRADO DE',221);
INSERT INTO colecciones (nombre, editorial) VALUES ('LIBROS CUPULA',389);
INSERT INTO colecciones (nombre, editorial) VALUES ('BIBLIOTECA PENSAMIENTO CRITICO',386);
INSERT INTO colecciones (nombre, editorial) VALUES ('ATLAS CULTURALES DEL MUNDO',148);
INSERT INTO colecciones (nombre, editorial) VALUES ('HOMBRES Y PAISSES',390);
INSERT INTO colecciones (nombre, editorial) VALUES ('EL MUNDO DEL ARTE',32);
INSERT INTO colecciones (nombre, editorial) VALUES ('RUTAS DE LA MEMORIA',391);
INSERT INTO colecciones (nombre, editorial) VALUES ('VOCES LITERATURA',396);
INSERT INTO colecciones (nombre, editorial) VALUES ('ESPAÑOL LENGUA EXTRANJERA',2);
INSERT INTO colecciones (nombre, editorial) VALUES ('NOVELA HISTORICA DE EGIPTO',34);
INSERT INTO colecciones (nombre, editorial) VALUES ('KRK PENSAMIENTO',393);
INSERT INTO colecciones (nombre, editorial) VALUES ('MINILIBROS AUTOAYUDA',392);
INSERT INTO colecciones (nombre, editorial) VALUES ('GRANDES ESCRITORAS',34);
INSERT INTO colecciones (nombre, editorial) VALUES ('MAESTROS DEL TERROR',9);
INSERT INTO colecciones (nombre, editorial) VALUES ('ATLAS VISUAL PATRIMONIO DE LA HUMANIDAD',34);
INSERT INTO colecciones (nombre, editorial) VALUES ('SERIE MONOGRAFIAS',399);
INSERT INTO colecciones (nombre, editorial) VALUES ('BASICA DE BOLSILLO',407);
INSERT INTO colecciones (nombre, editorial) VALUES ('GUIAS VISUALES',400);
INSERT INTO colecciones (nombre, editorial) VALUES ('LOS TRES MUNDOS',57);
INSERT INTO colecciones (nombre, editorial) VALUES ('LITERATURA ALIANZA EDITORIAL',13);
INSERT INTO colecciones (nombre, editorial) VALUES ('GUIAS OCEANO',118);
INSERT INTO colecciones (nombre, editorial) VALUES ('OTRAS LENGUAS',150);
INSERT INTO colecciones (nombre, editorial) VALUES ('BOLSILLO E',126);
INSERT INTO colecciones (nombre, editorial) VALUES ('ALBA MINUS',1);
INSERT INTO colecciones (nombre, editorial) VALUES ('CLASICO ZETA',157);
INSERT INTO colecciones (nombre, editorial) VALUES ('BIBLIOTECA PEREZ REVERTE',44);
INSERT INTO colecciones (nombre, editorial) VALUES ('GRANDES CIVILIZACIONES',34);
INSERT INTO colecciones (nombre, editorial) VALUES ('LA OTRA ORILLA',384);
INSERT INTO colecciones (nombre, editorial) VALUES ('LOS ESCRITORES Y LA MUSICA',416);
INSERT INTO colecciones (nombre, editorial) VALUES ('PENSAMIENTO',418);
INSERT INTO colecciones (nombre, editorial) VALUES ('FUTURA',4);
INSERT INTO colecciones (nombre, editorial) VALUES ('NARRATIVA',65);
INSERT INTO colecciones (nombre, editorial) VALUES ('DOSSOLES HISTORIA',420);
INSERT INTO colecciones (nombre, editorial) VALUES ('SERIE AZUL',203);
INSERT INTO colecciones (nombre, editorial) VALUES ('VIVENCIAS',419);
INSERT INTO colecciones (nombre, editorial) VALUES ('NOVELA NEGRA',386);
INSERT INTO colecciones (nombre, editorial) VALUES ('MEMORIA MUNDI',425);
INSERT INTO colecciones (nombre, editorial) VALUES ('BIBLIOTECA DE LA MEMORIA',423);
INSERT INTO colecciones (nombre, editorial) VALUES ('NARRATIVA CONTEMORANEA',421);
INSERT INTO colecciones (nombre, editorial) VALUES ('ARGUMENTOS',22);
INSERT INTO colecciones (nombre, editorial) VALUES ('TRAS 3 LETRAS',393);
INSERT INTO colecciones (nombre, editorial) VALUES ('OCTAVO MAYOR',393);
INSERT INTO colecciones (nombre, editorial) VALUES ('PAIDOS TESTIMONIOS',271);
INSERT INTO colecciones (nombre, editorial) VALUES ('ANAYA TOURING',2);
INSERT INTO colecciones (nombre, editorial) VALUES ('BIBLIOTECA SARAMAGO',44);
INSERT INTO colecciones (nombre, editorial) VALUES ('EDILESA PATRIMONIO',126);
INSERT INTO colecciones (nombre, editorial) VALUES ('ARTE EN ESPAÑA',237);
INSERT INTO colecciones (nombre, editorial) VALUES ('THE BRITISH LIBRARY',426);
INSERT INTO colecciones (nombre, editorial) VALUES ('PRIMERA PERSONA',394);
INSERT INTO colecciones (nombre, editorial) VALUES ('JOYAS LITERARIAS',35);
INSERT INTO colecciones (nombre, editorial) VALUES ('BIBLIOTECA VARGAS LLOSA',44);
INSERT INTO colecciones (nombre, editorial) VALUES ('TH NOVELA',26);
INSERT INTO colecciones (nombre, editorial) VALUES ('NOVELAS ESPAÑOLAS CONTEMPORANEAS',429);
INSERT INTO colecciones (nombre, editorial) VALUES ('BIBLIOTECA DE LA HISTORIA',20);
INSERT INTO colecciones (nombre, editorial) VALUES ('NARRATIVA',430);
INSERT INTO colecciones (nombre, editorial) VALUES ('ALIANZA LITERARIA',13);
INSERT INTO colecciones (nombre, editorial) VALUES ('BIBLIOTECA FURTIVA',57);
INSERT INTO colecciones (nombre, editorial) VALUES ('ART POCKET',441);
INSERT INTO colecciones (nombre, editorial) VALUES ('SINGULAR',440);
INSERT INTO colecciones (nombre, editorial) VALUES ('ARTE Y ARQUITECTURA',441);
INSERT INTO colecciones (nombre, editorial) VALUES ('BIBLIOTECA CLASICA DE LA RAE',443);
INSERT INTO colecciones (nombre, editorial) VALUES ('GIGAMESH FICCION',444);
INSERT INTO colecciones (nombre, editorial) VALUES ('LARGO RECORRIDO',447);
INSERT INTO colecciones (nombre, editorial) VALUES ('GUIAS TRES D',2);
INSERT INTO colecciones (nombre, editorial) VALUES ('EL ACANTILADO',91);
INSERT INTO colecciones (nombre, editorial) VALUES ('NUEVOS TIEMPOS',51);
INSERT INTO colecciones (nombre, editorial) VALUES ('NARRATIVA CLASICOS',421);
INSERT INTO colecciones (nombre, editorial) VALUES ('NARRATIVAS GALLO NERO',448);
INSERT INTO colecciones (nombre, editorial) VALUES ('MEMORIA DE LA HISTORIA',26);
INSERT INTO colecciones (nombre, editorial) VALUES ('ALARIFE',131);
INSERT INTO colecciones (nombre, editorial) VALUES ('BIBIOTECA DOMINICANA',472);
INSERT INTO colecciones (nombre, editorial) VALUES ('NARRATIVAS',34);
INSERT INTO colecciones (nombre, editorial) VALUES ('BIBLIOTECA DOMINICANA',472);
INSERT INTO colecciones (nombre, editorial) VALUES ('HISTORIA Y VIDA',26);
INSERT INTO colecciones (nombre, editorial) VALUES ('PAISAJES NARRADOS',92);
INSERT INTO colecciones (nombre, editorial) VALUES ('VOCES DEL ESTE',355);
INSERT INTO colecciones (nombre, editorial) VALUES ('RELIGIONES DEL MUNDO',407);
INSERT INTO colecciones (nombre, editorial) VALUES ('LOS CAMINOS DE LA NATURALEZA',177);
INSERT INTO colecciones (nombre, editorial) VALUES ('OTRAS LATITUDES',385);
INSERT INTO colecciones (nombre, editorial) VALUES ('TAURUS HISTORIA',418);
INSERT INTO colecciones (nombre, editorial) VALUES ('BIBLIOTECA KADARE',13);
INSERT INTO colecciones (nombre, editorial) VALUES ('BEST BOOK',75);
INSERT INTO colecciones (nombre, editorial) VALUES ('BIBLIOTECA AVREA',10);
INSERT INTO colecciones (nombre, editorial) VALUES ('CLASICOS',484);
INSERT INTO colecciones (nombre, editorial) VALUES ('NOVELA HISORICA',57);
INSERT INTO colecciones (nombre, editorial) VALUES ('ITACAS',475);
INSERT INTO colecciones (nombre, editorial) VALUES ('MUNDO INSOLITO',491);
INSERT INTO colecciones (nombre, editorial) VALUES ('TURNER MUSICA',125);
INSERT INTO colecciones (nombre, editorial) VALUES ('TIEMPO DE HISTORIA',27);
INSERT INTO colecciones (nombre, editorial) VALUES ('GUIA AZUL',229);
INSERT INTO colecciones (nombre, editorial) VALUES ('ESPIRAL',486);
INSERT INTO colecciones (nombre, editorial) VALUES ('VIAJES Y COSTUMBRES',490);
INSERT INTO colecciones (nombre, editorial) VALUES ('MAXI',7);
INSERT INTO colecciones (nombre, editorial) VALUES ('EDICIONES A LA CARTA',488);
INSERT INTO colecciones (nombre, editorial) VALUES ('ENTRELINEAS',487);
INSERT INTO colecciones (nombre, editorial) VALUES ('CLASICOS',79);
INSERT INTO colecciones (nombre, editorial) VALUES ('SILLON OREJERO',493);
INSERT INTO colecciones (nombre, editorial) VALUES ('TIMUNMAS',389);
INSERT INTO colecciones (nombre, editorial) VALUES ('GUIAS TURISTICAS',502);
INSERT INTO colecciones (nombre, editorial) VALUES ('TURISMO',16);
INSERT INTO colecciones (nombre, editorial) VALUES ('IBERICA',16);
INSERT INTO colecciones (nombre, editorial) VALUES ('COLECCIÓN DE ESTUDIOS ALTOARAGONESES',499);
INSERT INTO colecciones (nombre, editorial) VALUES ('PLAZA JOVEN',5);
INSERT INTO colecciones (nombre, editorial) VALUES ('NUESTRA TIERRA',113);
INSERT INTO colecciones (nombre, editorial) VALUES ('BIBLIOTECA DE TRADUCTORES',13);
INSERT INTO colecciones (nombre, editorial) VALUES ('CUADERNOS ALFABIA',521);
INSERT INTO colecciones (nombre, editorial) VALUES ('MAESTROS DE LA LITERATURA JAPONESA',520);
INSERT INTO colecciones (nombre, editorial) VALUES ('BESTIARIOS',522);
INSERT INTO colecciones (nombre, editorial) VALUES ('IRIA',523);
INSERT INTO colecciones (nombre, editorial) VALUES ('AVATARES',79);
INSERT INTO colecciones (nombre, editorial) VALUES ('ENSAYO HISTORICO',49);
INSERT INTO colecciones (nombre, editorial) VALUES ('GUIAS ESPINO ALBAR',525);
INSERT INTO colecciones (nombre, editorial) VALUES ('LA CONJURA DE LA RISA',22);
INSERT INTO colecciones (nombre, editorial) VALUES ('AUDIOBOOKS/LIBROS BILINGUES',526);
INSERT INTO colecciones (nombre, editorial) VALUES ('GRANDES CLASICOS DE LA NOVELA NEGRA',34);
